<a href="https://colab.research.google.com/github/aso1901104/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## sklearnでエラーが出るので、前のバージョンを入れ直す(0.22を消して0.20を入れる)

In [2]:
# # 現在のsckit-learnをcolabのVMからアンインストール
# !pip uninstall scikit-learn
# # 前のバージョンを指定してVMにインストール
# !pip install scikit-learn==0.20 --ignore-installed

## all_estimators()でループして各種のアルゴリズムで学習してさせ、比較する

In [3]:
# ライブラリの読込
import pandas as pd
# 学習用データとテスト検証用データを分割するライブラリ
from sklearn.model_selection import train_test_split
# 正解率を産出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimators(推定器の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.utils.testing module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.utils. Anything that cannot be imported from sklearn.utils is now part of the private API.
  warnings.warn(message, FutureWarning)


### webからアヤメのデータを読み込む


In [4]:
# urlリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
# リンクから保存するためのフィアルを定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへ保存
req.urlretrieve(url, savefile)
# pandasのread_csvメソッドを使ってCSVファイルを読み込む
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

### アヤメデータを目的変数:y（ラベル）と説明変数:x(入力データ)に分離する

In [5]:
y = iris_data.loc[:, "Name"] # 目的変数
x = iris_data.loc[:, ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"] ] # 説明変数
print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


### アヤメデータをさらに学習用とテスト検証用に分離する

In [6]:
# 学習用データ(train)とテスト検証用データ(test)に分離
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8, shuffle=True)
print(x_train.head())
print(x_test.head())
print(y_train.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
149          5.9         3.0          5.1         1.8
55           5.7         2.8          4.5         1.3
101          5.8         2.7          5.1         1.9
38           4.4         3.0          1.3         0.2
143          6.8         3.2          5.9         2.3
    SepalLength  SepalWidth  PetalLength  PetalWidth
2           4.7         3.2          1.3         0.2
88          5.6         3.0          4.1         1.3
49          5.0         3.3          1.4         0.2
43          5.0         3.5          1.6         0.6
0           5.1         3.5          1.4         0.2
149     Iris-virginica
55     Iris-versicolor
101     Iris-virginica
38         Iris-setosa
143     Iris-virginica
Name: Name, dtype: object
2         Iris-setosa
88    Iris-versicolor
49        Iris-setosa
43        Iris-setosa
0         Iris-setosa
Name: Name, dtype: object


### allAlgolithmsにclassifierを指定して「分類」でフィルターしたアルゴリズムの推定器を取得する

In [7]:
# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings("ignore")

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


### 推定器のリストをループしながら学習＆推論させる

### sklearnでエラーが出る

In [8]:
# 推定器のリストをループ
for (name, algorithm) in allAlgorithms:
  # pythonでのtry-catch(try-except)
  try: # pythonのtry
    # 各アルゴリズムのオブジェクトを生成
    clf = algorithm() # 各アルゴリズムのクラスのコンストラクタを実行
    # 学習させる(fitメソッド)
    clf.fit(x_train, y_train)
    # 推論する
    y_pred = clf.predict(x_test)
    # accuracy_scoreで正解率を産出して表示
    print(name, "の正解率 = ", accuracy_score(y_test, y_pred))
  except Exception as e: #pythonのcatch(except)
    print("\033[31m" , " Error: \033[0m", name, ":" , e.args)
    # print("エラーです")
  else:
    # print("エラー以外")
    pass
# for終了

AdaBoostClassifier の正解率 =  0.9333333333333333
BaggingClassifier の正解率 =  0.9666666666666667
BernoulliNB の正解率 =  0.2
CalibratedClassifierCV の正解率 =  0.9333333333333333
CategoricalNB の正解率 =  0.9333333333333333
  Error:  CheckingClassifier : ("could not convert string to float: 'Iris-virginica'",)
  Error:  ClassifierChain : ("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率 =  0.6333333333333333
DecisionTreeClassifier の正解率 =  0.9666666666666667
DummyClassifier の正解率 =  0.23333333333333334
ExtraTreeClassifier の正解率 =  1.0
ExtraTreesClassifier の正解率 =  0.9666666666666667
GaussianNB の正解率 =  1.0
GaussianProcessClassifier の正解率 =  0.9666666666666667
GradientBoostingClassifier の正解率 =  0.9666666666666667
HistGradientBoostingClassifier の正解率 =  0.9666666666666667
KNeighborsClassifier の正解率 =  0.9666666666666667
LabelPropagation の正解率 =  0.9666666666666667
LabelSpreading の正解率 =  0.9666666666666667
LinearDiscriminantAnalysis の正解率 =  0.9666666666666667
LinearSVC の正解率 

## クロスバリデーション 

### クロスバリデーション関連のライブラリのインポート

In [9]:
# ライブラリのインポート
# K分割クロスバリデーション(交差検証)のためのライブラリ
from sklearn.model_selection import KFold
# クロスバリデーションスコアを取得するためのオブジェクト
from sklearn.model_selection import cross_val_score

### クロスバリデーションを実行する

In [10]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold( n_splits=5, shuffle=True )
# 既に生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for ( name, algorithm ) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr( clf, "score" ):
      # クロスバリデーション をしてスコアを取得する
      scores = cross_val_score( clf, x, y, cv=kfold_cv )
      # k=n_splits=5回分のクロスバリデーション のスコアを表示
      print(name, "の正解率 = ")
      print( scores )
  except:
    pass
   

AdaBoostClassifier の正解率 = 
[0.93333333 0.96666667 0.9        0.93333333 0.93333333]
BaggingClassifier の正解率 = 
[0.96666667 0.96666667 0.93333333 0.96666667 0.93333333]
BernoulliNB の正解率 = 
[0.26666667 0.2        0.3        0.2        0.23333333]
CalibratedClassifierCV の正解率 = 
[0.93333333 0.9        0.9        0.9        0.93333333]
CategoricalNB の正解率 = 
[0.9        0.96666667 0.96666667 0.96666667 0.86666667]
CheckingClassifier の正解率 = 
[nan nan nan nan nan]
ComplementNB の正解率 = 
[0.66666667 0.7        0.83333333 0.6        0.53333333]
DecisionTreeClassifier の正解率 = 
[0.96666667 0.93333333 0.93333333 0.9        1.        ]
DummyClassifier の正解率 = 
[0.23333333 0.33333333 0.5        0.33333333 0.4       ]
ExtraTreeClassifier の正解率 = 
[0.9        0.9        0.93333333 1.         0.96666667]
ExtraTreesClassifier の正解率 = 
[0.9        0.96666667 0.96666667 0.93333333 1.        ]
GaussianNB の正解率 = 
[0.96666667 1.         0.93333333 0.93333333 0.96666667]
GaussianProcessClassifier の正解率 = 
[0.96666667 

### おまけ：cross_val_scoreよりも、もっと詳しい結果を取得できる新しいクロスバリデーションオブジェクト：cross_validate

In [11]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション 

In [12]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold( n_splits=5, shuffle=True )
# 既に生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for ( name, algorithm ) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf = algorithm()
    # scoreの属性がある学習モデルだけに絞る
    if hasattr( clf, "score" ):
      # cross_validateでクロスバリデーションをしてスコアを取得する
      scores = cross_validate( clf, x, y, cv=kfold_cv )
      # k=n_splits=5回分のクロスバリデーション のスコアを表示
      print(name, "の正解率 = ")
      print( scores )
  except:
    pass
   

AdaBoostClassifier の正解率 = 
{'fit_time': array([0.08899641, 0.06777072, 0.07076836, 0.06718278, 0.06666565]), 'score_time': array([0.00713682, 0.00707245, 0.00686526, 0.00687718, 0.00794649]), 'test_score': array([0.93333333, 0.96666667, 0.93333333, 1.        , 0.93333333])}
BaggingClassifier の正解率 = 
{'fit_time': array([0.01766109, 0.01654077, 0.01561308, 0.01590371, 0.01578879]), 'score_time': array([0.00243092, 0.00235963, 0.00239062, 0.00238538, 0.00255084]), 'test_score': array([0.93333333, 0.93333333, 0.96666667, 1.        , 0.96666667])}
BernoulliNB の正解率 = 
{'fit_time': array([0.00319862, 0.00253081, 0.00198197, 0.00189853, 0.00188637]), 'score_time': array([0.00146699, 0.00160742, 0.00099325, 0.00097132, 0.00097585]), 'test_score': array([0.3       , 0.26666667, 0.26666667, 0.13333333, 0.16666667])}
CalibratedClassifierCV の正解率 = 
{'fit_time': array([0.05915666, 0.06139398, 0.05876446, 0.05699992, 0.06046677]), 'score_time': array([0.00200891, 0.00193787, 0.00192332, 0.00188494, 0

## グリッドサーチで最適なパラメータを探し求める

In [13]:
#　ライブラリをインポート
from sklearn.model_selection import GridSearchCV
# SVCあるゴリズムの学習モデルをimport
from sklearn.svm import SVC

### グリッドサーチを実行してパラメータを試す

In [14]:
# グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              # 3つのパラメータ、3パターン
              { "C": [1, 10, 100, 1000], "kernel": ["linear"] },
              { "C": [1, 10, 100, 1000], "kernel": ["rbf"], "gamma": [0.001, 0.0001] },
              { "C": [1, 10, 100, 1000], "kernel": ["sigmoid"], "gamma": [0.001, 0.0001] }
]
# 普通の学習
clf_svc = SVC()
clf_svc.fit(x_train, y_train)
y_pred_svc = clf_svc.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test, y_pred_svc))

# グリッドサーチを行う
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold( n_splits=5, shuffle=True )
# グリッドサーチの中でK分割交差検証も行われる
clf_gird = GridSearchCV( SVC(), parameters, cv=kfold_cv ) # インスタンス
clf_gird.fit( x_train, y_train ) # 学習
# 学習済みのモデルに設定された最適と思われるパラメータを表示
print("最適なパラメータ　 = ", clf_gird.best_estimator_ )

# 最適なパラメータで評価
y_pred_svc = clf_gird.predict(x_test)
print("グリッドサーチの正解率 = ", accuracy_score(y_test, y_pred_svc))

普通の学習の正解率 =  0.9666666666666667
最適なパラメータ　 =  SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9666666666666667


## Numpyの動作確認

In [15]:
# numpyのインポート
import numpy as np

In [16]:
# numpy配列の初期化
a = np.array( [1, 2, 3, 4, 5] ) # ndarrayというnumpy配列オブジェクトを生成
print(a)
# type関数で型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
# 2次元のndarrayを定義
b = np.array( [[1, 2, 3], [4, 5, 6]] )
print(b)

[[1 2 3]
 [4 5 6]]


In [18]:
# 配列の要素数を指定して0埋めで初期化
print( np.zeros(10) )
print( np.zeros((3, 2)) )
print( np.ones(2) )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [19]:
# 連番の配列を要素数を指定して初期化
print( np.arange(5) )
print( np.arange(2, 9) )
print( np.arange(5, 8, 0.5) )

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


In [20]:
a = np.array( [1, 2, 3, 4, 5] )
b = a*2 # 全ての要素を一度に2倍
print(b)
x = np.arange(10)
print(x)
y = 3*x + 5 # 全ての要素に一度に四則演算
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [21]:
# 配列の次元数を表示
a = np.array( [[1, 2, 3], [4, 5, 6]] )
print(a)
print(a.shape)

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)
print(b.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [35]:
# Numpy配列で次元数を変換する
a = np.array( [[1, 2, 3], [4, 5, 6]] )
print("a = ", a, "\n")
b = a.flatten() # フラットにする(1次元配列にする)
print("b = ", b, "\n")

a = np.array( [[1, 2, 3], [4, 5, 6]] ) # ２行3列
print(a, "\n")
b = a.reshape(3,2) # 3行2列に回転(変換)
print(b)

a =  [[1 2 3]
 [4 5 6]] 

b =  [1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


### numpyの配列にアクセスする方法

In [31]:
v = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]] )
a = v[0]
print(a, "\n") # 2次元配列の0行目
b = v[1:]
print(b, "\n") # 1行目以降
c = v[:, 0]
print(c) # 全ての行の0列目

[1 2 3] 

[[4 5 6]
 [7 8 9]] 

[1 4 7]
